hr/urls.py
from django.urls import path
from hr import views
from django.conf import settings
from django.conf.urls.static import static

#general urls
app_name = 'hr'

""" URLs used in the HR application. """
urlpatterns = [
    path('recruitment/', views.RecruitmentView.as_view(), name='recruitment'),
    path('jobDescription/', views.JobDescriptionView.as_view(), name='jobDescription'),
    path('approveRequest/', views.ApproveRequestView.as_view(), name='approveRequest'),
    path('requestList/', views.RequestListView.as_view(), name='requestList'),
    path('jobVacancy/', views.JobVacancyAdvertisementView.as_view(), name='jobVacancy'),
    path('receiveCVs/', views.ReceiveCVsView.as_view(), name='receiveCV'),
    path('selectIC/', views.SelectInicialCandidatesView.as_view(), name='selectIC'),
    path('selectC/', views.SelectCandidateView.as_view(), name='selectC'),

]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# general imports
from django import views
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(),name="Home"),
    path('shop/', views.Shop.as_view(), name="shop")    
]

shop/urls.py
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'shop'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='summary'),   
    path('product/', views.ProductListView, name='product'),
    path('<str:parent_or_child>/<int:pk>', views.ProductListView, name='product_cat'),
    path('search/', views.search, name="search"), 
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import View
from . import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'user'
urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(),name='login'),
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup' ),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update' ),
    path(route='<str:username>/', view=views.UserDetailView.as_view(), name='detail' ),
]

if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from tabnanny import verbose
from django import forms
from django.forms import fields
from django.utils.translation import ugettext_lazy as _

from shop.models import OrderItem

#contact form class
class Contactf(forms.Form):
    Name = forms.CharField(label = _('Name'), 
        max_length=100, 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your Name")
    }))
    Last_name = forms.CharField(label = _('Last name'),
        max_length=100, 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your Last Name")
    }))
    Email = forms.EmailField(label = _('Email'), 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your e-mail")
    }))
    Message = forms.CharField(label = _('Message'),
        widget=forms.Textarea(attrs={ 'placeholder': _("Your Message")
    }))

class AddToCartForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        fields = ['quantity']
        help_texts = {'quantity': None,}
        verbose_name = _('quantity')

shop/views.py
from django.db.models.query import InstanceCheckMeta
from django.http import request, JsonResponse, response, Http404
from django.shortcuts import reverse, get_object_or_404, redirect, render
from django.views import generic
from django.core.mail import send_mail
from django.conf import settings 
from django.contrib import messages 
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from shop.forms import Contactf, AddToCartForm
from shop.models import Category, Product, OrderItem, SubCategory
from shop.utils import get_or_set_order_session



# Create your views here.


class ContactView(generic.FormView):
    form_class = Contactf
    template_name = "contact.html"

    def get_success_url(self):        
        return reverse("shop:contact")
    
    def form_valid(self, form):
        messages.info(
            self.request, "We have received your message ")
        Name = form.cleaned_data.get('Name')
        Last_name = form.cleaned_data.get('Last_name')
        Email = form.cleaned_data.get('Email')
        Message = form.cleaned_data.get('Message')

        full_message = f"""
            Message received from {Name},{Last_name}, {Email}
            ___________________________________


            {Message}
            """
        send_mail(
            subject="Message received by Contact Form",
            message=full_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.NOTIFY_EMAIL]
        )
        return super(ContactView, self).form_valid(form)

def search(request):
    if request.method == "POST":
        search = request.POST['search']
        product = Product.objects.filter(title__icontains=search)
        return render(request, 'product_list.html', {'search':search, 'product':product})
    else:
        return render(request, 'product_list.html', {})

def ProductListView(request, parent_or_child=None, pk=None):
    categories = Category.objects.filter(parent=None)
    
    if parent_or_child is None:
        products = Product.objects.all()
        paginator = Paginator(products, 6)
            
    elif parent_or_child == 'child':
        sub_cat= SubCategory.objects.get(pk=pk)
        products= sub_cat.product_set.all()
        paginator = Paginator(products, 6)
            
    elif parent_or_child == 'parent':
        products= []
        sub_cats= Category.objects.get(pk=pk).children.all()

        for sub_cat in sub_cats:
            prds = sub_cat.product_set.all()
            products += prds
        paginator = Paginator(products, 6)
            
    else:
        products = []        
          
    page = request.GET.get('page')
 
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products= paginator.page(paginator.num_pages)

    return render(
        request,
        'product_list.html',
        {'categories': categories, 'products': products, }
    )
    
class ProductDetailView(generic.FormView):
    template_name='product_detail.html'
    form_class = AddToCartForm
    
    def get_object(self):
        return get_object_or_404(Product, slug = self.kwargs["slug"])

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            order = get_or_set_order_session(self.request)
            product = self.get_object()
            form = self.form_class(request.POST)
            item_filter = order.items.filter(product = product)

            if form.is_valid():
                if item_filter.exists():
                    item = item_filter.first()
                    item.quantity += int(form.cleaned_data['quantity'])
                    item.save()
                    msg = "sumar item"
                    error = form.errors
                else:
                    new_item = form.save(commit=False)
                    new_item.product = product
                    new_item.order = order
                    new_item.save()
                    msg = "nuevo item"
                    error = form.errors
                response = JsonResponse({'mensaje':msg,'error':error})
                return response    
            else:
                msg = "form no valido"
                error = form.errors
                response = JsonResponse({'mensaje':msg,'error':error})
                print(form.errors)
                return response
    
    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context

class CartView(generic.TemplateView):
    template_name = "cart.html"
    def get_context_data(self, *args,**kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("shop:summary")

class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("shop:summary")

class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("shop:summary")

shop/templates/cart.html
{% extends "indexx.html" %}
{% load i18n%}
{% block title %}
    {% trans "Cart" %}
{% endblock title %}
{% block content %}

<div id="content" class="m-3 p-3">
    <div class="container bg-white ">
        <div class="row">
            <div id="checkout" class="col-lg-9">
                <div class="box">
                    <div class="content">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>{% trans "Image" %}</th>
                                        <th>{% trans "Product" %}</th>
                                        <th>{% trans "Price" %}</th>
                                        <th>{% trans "Quantity" %}</th>
                                        <th>{% trans "Total" %}</th>
                                        <th>{% trans "Actions" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <img src="{{ item.product.image.url }}" class="img-fluid">
                                        </td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black" >{{ item.product.title }}</h2>
                                        </td>
                                        <td>{{ item.product.get_price }}</td>
                                        <td>
                                            <div class="input-group"  style="max-width: 120px;">
                                                <div class="input-group-pretend ">
                                                    <a href="{% url 'shop:decrease-quantity' item.id %}"
                                                        class="btn btn-outline-primary"
                                                        style="margin-top: 0px;">
                                                        &minus;
                                                    </a>
                                                </div>
                                                <input type="text" class="form-control text-center"
                                                    value="{{ item.quantity }}"
                                                >
                                                <div class="input-group-append">
                                                    <a href="{% url 'shop:increase-quantity' item.id %}"
                                                        class="btn btn-outline-primary"
                                                        style="margin-top: 0px;">
                                                        &plus;
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            {{ item.get_total_item_price }}
                                        </td>
                                        <td>
                                            <a href="{% url 'shop:remove-from-cart' item.id %}"
                                                class="btn btn-outline-primary ">x</a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="6">{% trans "There are no items in your cart." %} 
                                            <a href="{% url 'shop:product' %}">
                                                {% trans "Continue Shopping" %}
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="4">Total</th>
                                        <th>{{ order.get_subtotal }}</th>
                                    </tr>
                                </tfoot>
                            </table>
                            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row mb-5">
                                    <div class="col-md-12">
                                        <a class="btn btn-outline-primary btn-sm btn-block"
                                        href="{% url 'shop:product' %}">{% trans "Continue Shopping" %}</a>
                                    </div>
                                </div>
                            </div>               
                        </div>
                    </div>

                </div>
            </div>

            {% if order.items.count > 0 %}
               
                <div class="col-lg-3">
                    <div id="order-summary" class="box mb-4 p-0">
                        <div class="box-header mt-0 bg-white">
                            <h3>{% trans "Order summary" %}</h3>
                        </div>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Subtotal</td>
                                        <th>{{ order.get_subtotal }}</th>
                                    </tr>
                                    <tr>
                                        <td>{% trans "Shipping Cost" %}</td>
                                        <th>$0</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th>{{ order.get_total }}</th>
                                    </tr>
                                </tbody>
                            </table>                            
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="#" class="btn btn-outline-primary btn-lg py-3 btn-block">{% trans "Proceed to Checkout" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

shop/templates/checkout.html
{% extends "home.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Checkout" %}
{% endblock title %}

{% block content %}

<div class="site-section p-3">
    <div class="container bg-white p-3">
        {% if not request.user.is_authenticated %}
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="border p-4 rounded" role="alert">
                    {% trans "Your are nearly finished with your order." %}
                    {% trans "To finalize your order, please" %}
                    <a href="{% url 'user:login' %}">{% trans "Login" %}</a> {% trans "or" %}<a href="{% url 'user:signup' %}">{% trans "SignUp" %}</a>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-label="90" aria-valuemin="0"
                        aria-valuemax="100">
                        {% trans "90% Complete" %}
                    </div>
                </div>
            </div>
        </div>
        {% else %}        
            <div class="row">
                <div class="col-md-7 mb-md-0">
                    <h2 class="h3 mb-3 text-black text-center">{% trans "Billing Details" %}</h2>
                    <hr />
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="p-2 p-lg-2">
                            <label for="selected_shipping_address">{% trans "Select Shipping Address" %}</label>
                            {{ form.selected_shipping_address }}
                        </div>
                        <div class="p-2 p-lg-2">
                            <label for="selected_billing_address">{% trans " Select Billing Address" %}</label>
                            {{ form.selected_billing_address }}
                        </div>
                        <div class="card card-header p-0 mb-0 mt-2">
                            <a class="btn bg-gray btn-block text-left collapsed" data-toggle="collapse" data-target="#address" aria-expanded="false" aria-controls="address">
                                <i class="fa fa-angle-down mr-1"></i> {% trans "Add new addresses" %}
                            </a>                            
                        </div>
                        <div id="address"class="collapse">
                            <div class="card card-body">                                
                                <div class="form-group row">
                                    <label for="id_shipping_address_line_1" class="col-3 col-form-label">{% trans " Shipping Address" %}:</label>
                                    <div class="col-9">
                                        {{ form.shipping_address_line_1 }}
                                    </div>
                                </div>                       
                                <div class="form-group row">
                                    <label for="id_shipping_zip_code" class="col-3 col-form-label">{% trans " Shipping Zip code" %}:</label>
                                    <div class="col-9">
                                        {{ form.shipping_zip_code }}
                                    </div>
                                </div>                           
                                <div class="form-group row">
                                    <label for="id_shipping_city" class="col-3 col-form-label">{% trans "Shipping City" %}:</label>
                                    <div class="col-9">
                                        {{ form.shipping_city }}
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <label for="id_shipping_address_line_1" class="col-3 col-form-label">{% trans " Billing Address" %}:</label>
                                    <div class="col-9">
                                        {{ form.billing_address_line_1 }}
                                    </div>
                                </div>                       
                                <div class="form-group row">
                                    <label for="id_shipping_zip_code" class="col-3 col-form-label">{% trans " Billing Zip code" %}:</label>
                                    <div class="col-9">
                                        {{ form.billing_zip_code }}
                                    </div>
                                </div>                           
                                <div class="form-group row">
                                    <label for="id_shipping_city" class="col-3 col-form-label">{% trans "Billing City" %}:</label>
                                    <div class="col-9">
                                        {{ form.billing_city }}
                                    </div>
                                </div>                                  
                            </div>
                        </div> 
                        <div class="d-flex justify-content-center p-3">
                            <button type="submit" class="btn btn-success btn-md py-3">
                                {% trans "Proceed to Payment" %}
                            </button>
                        </div>
                    </form>        
                </div>
                <div class="col-md-5">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black text-center">{% trans "Your Order" %}</h2>
                            <hr>
                            <div class="p-3 p-lg-5">
                                <table class="table site-block-order-table mb-2">
                                    <thead>
                                        <th>{% trans "Product" %}</th>
                                        <th>{% trans "Total" %}</th>
                                    </thead>
                                    <tbody>
                                        {% for item in order.items.all %}
                                        <tr>
                                            <td>
                                                {{ item.product.title }}
                                                <strong class="mx-2">x</strong> {{ item.quantity }}
                                            </td>
                                            <td>
                                                $ {{ item.get_total_item_price }}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        <tr>
                                            <td><strong class="text-black font-weight-bold">{% trans "Subtotal" %}</strong></td>
                                            <td>$ {{ order.get_subtotal }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>{% trans "Order Total" %}</strong></td>
                                            <td><strong class="text-black font-weight-bold">$ {{ order.get_total }}</strong></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

shop/templates/contact.html
{% extends "indexx.html" %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %}
    {% trans "Contact" %}
{% endblock title %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'Home' %}">{% trans "Home" %}</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">{% trans "Contact" %}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">{% trans "Get in touch" %}</h2>
            </div>

            <div class="col-md-7">
                <form method="POST"> 
                    {% csrf_token %}
                    {{ form|crispy}}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="{% trans 'Submit message' %}"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

shop/templates/failure.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Payment not made!</h1>
    <p>
        Something happened and the payment did not go through. Please try again. 
        If the error persists, please contact us.
    </p>
    <a class="btn btn-primary" href="{% url 'payments:process' %}">
        Try again
    </a>
</div>

{% endblock %}

shop/templates/payment_successful.html
{% extends "home.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Payment Successful" %}{%endblock title%}

{% block content %}

<div id="content" class=" m-3 p-3 p-bottom-2">
  <div class="payment border">
    <div class="payment_header">
       <div class="check"><i class="fa fa-check" aria-hidden="true" style="color:rgba(79, 191, 168, 0.9)"></i></div>
    </div>
  <div class="container bg-white p-3">
    <h1 class="text-center"> {% trans "Payment Successful" %} </h1>
    <p class="text-center">{% trans "Thank you for your purchase" %}</p>
    <div class="d-flex justify-content-center p-3" >
      <a href="{% url 'main:shop'%}" class="btn btn-primary btn-md py-3 w-25 rounded" >{% trans "Go to Home" %}</a>
    </div>  
  </div>  
</div>
{% endblock %}



   

shop/templates/pending.html
{% extends "base.html" %}

{% block title %}Success!{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">We are processing your payment!</h1>
    <p>
        Thank you for purchasing from us.
        Within 2 business days you will receive an e-mail with more information about the payment
    </p>
</div>

{% endblock %}

shop/templates/product_list.html
{% extends "indexx.html" %}
{% load i18n %}
{% block title %}
    {% trans "Shop" %}
{% endblock title %}

{% block content %}

<div class="site-section m-5">
    <div class="container-fluid ">
        <div class="row">
            <div class="col-md-9 bg-white p-3 ml-5">
                <div class="row mb-5">            
                    {% for product in products %}
                    <div class="col-lg-4 col-md-6 col-ms-6 mb-2 mt-5" data-aos='fade-up'>
        
                        <div class="d-flex align-products-start justify-content-center" >
                            <figure class="block-4-image ">
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="img-fluid img-responsive" style="height: 250px;" src="{{ product.image.url }}" alt="{{ product.title }}"> 
                                </a>
                            </figure>
                        </div>             
                        <div class="d-block justify-content-start block-4-text p-2">
                            <a href="{{ product.get_absolute_url }}">
                                <h3>{% trans product.title %}</h3>
                            </a>
                            <p class="mb-0">{% trans "Price" %}: {{ product.price }}</p>
                        </div>
                    </div>
                    {% endfor %}                    
                </div> 
                <div>
                    {% include 'pagination.html'%}
                    
                </div> 
    
            </div>            
                <!-- Category -->
            <div class="col-md-2  ml-3 p-3 border bg-white">
                <div class="panel panel-default sidebar-menu">
                    <div class="panel-heading">
                        <h3 class="h4 panel-title ">
                            <a href="{% url 'shop:product' %}" style="color:black;">
                                Categories 
                            </a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <ul class="nav nav-pills flex-column text-sm category-menu">
                            {% for category in categories %} 
                            <li class="nav-product">
                                <a href="{% url 'shop:product_cat' parent_or_child='parent' pk=category.id %}" 
                                    class="nav-link d-flex align-products-center justify-content-between">
                                    <span>{{ category }}</span>
                                </a>                                
                                {% for sub_cat in category.children.all %}
                                    <ul class="nav nav-pills flex-column">                      
                                        <li class="nav-product">
                                            <a href="{% url 'shop:product_cat' parent_or_child='child' pk=sub_cat.id %}" 
                                                class="nav-link">
                                                <span>{{ sub_cat }}</span>
                                            </a>
                                        </li>                                             
                                    </ul>
                                {% endfor %}                                
                            </li>
                            {% endfor %}                         
                        </ul>
                    </div>
                </div>
            </div>
             
        </div>
    </div>
</div>
{% endblock content %}